name: Unit Test
on:
  #schedule:
  #  - cron: "*/5 * * * *"
  push:
    inputs:
      browser:
        description: 'hello'
        required: true
        default: chrome

    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Write BROWSER value to Properties-file
      id: write_property1
      uses: Reedyuk/write-properties@v1.0.1
      with:
        path: './Configurations/configuration.properties'
        property: BROWSER
        value: ${{ github.event.inputs.browser }}

    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.1.0
      with:
        path: './Configurations/configuration.properties'
        properties: BROWSER UserName Password WEB_URL

    - name: Build with Maven
      run: mvn clean test -Punit-test

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
