name: Unit Test
on:
  #schedule:
  #  - cron: '41 * * * *'
  #push:
  #  branches: [ "master" ]

jobs:
  build:
    runs-on: windows
    steps:

    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'

    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.1.0
      with:
        path: './Configurations/configuration.properties'
        properties: BROWSER

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
