name: Workflow dispatch inputs
on:
  #schedule:
  #  - cron: "*/5 * * * *"

  #manually run workflow
  workflow_dispatch:
    inputs:
      browser:
        description: 'Input browser (chrome or IE)'
        required: true
        default: chrome
      url:
        description: 'Enter navigating url'
        required: true
        default: https://demo.guru99.com/v3/index.php
      username:
        description: 'Enter Username'
        required: true
        default: mngr26593
      password:
        description: 'Enter Password'
        required: true
        default: 123@123

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


      - name: Write BROWSER value to Properties-file
        id: write_property1
        uses: Reedyuk/write-properties@v1.0.1
        with:
          path: './Configurations/configuration.properties'
          property: BROWSER
          value: ${{ github.event.inputs.browser }}

      - name: Write URL value to Properties-file
        id: write_property2
        uses: Reedyuk/write-properties@v1.0.1
        with:
          path: './Configurations/configuration.properties'
          property: WEB_URL
          value: ${{ github.event.inputs.url }}

      - name: Write UserName value to Properties-file
        id: write_property3
        uses: Reedyuk/write-properties@v1.0.1
        with:
          path: './Configurations/configuration.properties'
          property: UserName
          value: ${{ github.event.inputs.username }}

      - name: Write Password value to Properties-file
        id: write_property4
        uses: Reedyuk/write-properties@v1.0.1
        with:
          path: './Configurations/configuration.properties'
          property: Password
          value: ${{ github.event.inputs.password }}

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './Configurations/configuration.properties'
          properties: BROWSER UserName Password URL

      - name: Build with Maven
        run: mvn test --batch-mode

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
